[package]
name = "extract-minecraft-assets"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
dirs = "6"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "2.5"
