[package]
name = "extract-hashed-minecraft-assets"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
crossterm = "0.28.1"
dirs = "6.0.0"

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
